### ISSUE TITLE
[Feature Request] Allow students with Google accounts whose regional settings are not set to Taiwan to access app

### ISSUE THREAD

**Issue by Allen050329** [morris13579/tat_ntust#2]
有少部份本國學生，及（大部分？）交換生的 Google 帳號將未地區設至台灣，亦有些人只用 Third-party Marketplace，因此未能安裝此程式；因此，希望能開放讓其他地區的帳號在 Google play 下載本程式，並於 F-Droid 上架，以便推廣。

**Comment by morris13579** [comment]
好的，目前已經開放其他國家下載，等能需要等待審核通過，您可以再確認看看。
由於我目前已經畢業，已經沒有學校帳號，未來學校如果修改網頁導致APP爬取資料錯誤，可能沒有辦法繼續維修。

**Comment by Allen050329** [comment]
Okay, thanks!!!
